<#
.SYNOPSIS
    Install and configure Syncthing for render farm asset pre-staging.
.DESCRIPTION
    Installs Syncthing via winget, configures it as a Windows service,
    and sets up send-only folders for render assets. Workers receive
    assets continuously in the background so files are local when jobs arrive.

    Idempotent — safe to run multiple times.
    Requires elevation (Run as Administrator).
.EXAMPLE
    gsudo .\Install-Syncthing.ps1
    gsudo .\Install-Syncthing.ps1 -ConfigPath .\farm-config.json
.NOTES
    After running, connect peer nodes via the Syncthing web UI at http://localhost:8384
    This machine is configured as Send-Only (authoritative source).
    Worker nodes should be configured as Receive-Only.
#>
#Requires -RunAsAdministrator
[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$ConfigPath = (Join-Path $PSScriptRoot 'farm-config.json')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

# --- Load config ---
if (-not (Test-Path $ConfigPath)) {
    Write-Host "  [FATAL] Config not found: $ConfigPath" -ForegroundColor Red
    exit 1
}
$Cfg = Get-Content $ConfigPath -Raw | ConvertFrom-Json

$script:changed = 0
$script:skipped = 0

function Log {
    param([string]$Msg, [ValidateSet('INFO','OK','SKIP','WARN','ERR')]$Lvl = 'INFO')
    $color = switch ($Lvl) {
        'OK'   { 'Green' }
        'SKIP' { 'DarkGray' }
        'WARN' { 'Yellow' }
        'ERR'  { 'Red' }
        default { 'Gray' }
    }
    $prefix = switch ($Lvl) { 'INFO' { '     ' } default { "[$Lvl] " } }
    Write-Host "  $prefix$Msg" -ForegroundColor $color
}

Write-Host ""
Write-Host "  Install-Syncthing — asset pre-staging" -ForegroundColor Cyan
Write-Host "  $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor DarkGray
Write-Host ""

# ===========================================================================
# 1. Install Syncthing
# ===========================================================================
Write-Host "  Install" -ForegroundColor White

$syncthing = Get-Command syncthing -ErrorAction SilentlyContinue
if ($syncthing) {
    $ver = & syncthing --version 2>&1 | Select-Object -First 1
    Log "Syncthing already installed: $ver" 'SKIP'; $script:skipped++
} elseif ($PSCmdlet.ShouldProcess('Syncthing', 'Install via winget')) {
    Write-Host "  Installing Syncthing..." -ForegroundColor DarkGray
    winget install --id Syncthing.Syncthing --accept-package-agreements --accept-source-agreements 2>&1 | Out-Null
    $syncthing = Get-Command syncthing -ErrorAction SilentlyContinue
    if ($syncthing) {
        Log "Syncthing installed" 'OK'; $script:changed++
    } else {
        Log "Syncthing install failed - install manually: winget install Syncthing.Syncthing" 'ERR'
        exit 1
    }
}

# ===========================================================================
# 2. Create Syncthing config directory
# ===========================================================================
Write-Host ""
Write-Host "  Configuration" -ForegroundColor White

$syncConfigDir = Join-Path $env:LOCALAPPDATA 'Syncthing'
if (-not (Test-Path $syncConfigDir)) {
    New-Item -Path $syncConfigDir -ItemType Directory -Force | Out-Null
    Log "Created config dir: $syncConfigDir" 'OK'; $script:changed++
} else {
    Log "Config dir exists: $syncConfigDir" 'SKIP'; $script:skipped++
}

# ===========================================================================
# 3. Create .stignore for render farm folders
# ===========================================================================
Write-Host ""
Write-Host "  Ignore patterns" -ForegroundColor White

$storageRoot = $Cfg.server.storage_root
$stignorePath = Join-Path $storageRoot '.stignore'
$ignorePatterns = $Cfg.syncthing.ignore_patterns -join "`n"
$desiredIgnore = @"
// Syncthing ignore patterns for render farm (generated by Install-Syncthing.ps1)
$ignorePatterns
*.sqlite
*.sqlite-journal
*.log
*.tmp
"@

if (Test-Path $stignorePath) {
    $current = Get-Content $stignorePath -Raw -ErrorAction SilentlyContinue
    if ($current.Trim() -eq $desiredIgnore.Trim()) {
        Log ".stignore unchanged" 'SKIP'; $script:skipped++
    } elseif ($PSCmdlet.ShouldProcess($stignorePath, 'Update .stignore')) {
        Set-Content -Path $stignorePath -Value $desiredIgnore -Encoding UTF8
        Log "Updated .stignore" 'OK'; $script:changed++
    }
} elseif ($PSCmdlet.ShouldProcess($stignorePath, 'Create .stignore')) {
    Set-Content -Path $stignorePath -Value $desiredIgnore -Encoding UTF8
    Log "Created .stignore at $stignorePath" 'OK'; $script:changed++
}

# ===========================================================================
# 4. Firewall rule
# ===========================================================================
Write-Host ""
Write-Host "  Firewall" -ForegroundColor White

$syncRule = Get-NetFirewallRule -DisplayName 'Syncthing' -ErrorAction SilentlyContinue
if ($syncRule) {
    Log "Firewall rule 'Syncthing' exists" 'SKIP'; $script:skipped++
} elseif ($PSCmdlet.ShouldProcess('Syncthing', 'Create firewall rule')) {
    try {
        New-NetFirewallRule -DisplayName 'Syncthing' -Direction Inbound `
            -LocalPort $Cfg.firewall.syncthing_port -Protocol TCP -Action Allow `
            -Profile Private -Description 'Syncthing asset sync' | Out-Null
        # Also allow UDP for discovery
        New-NetFirewallRule -DisplayName 'Syncthing Discovery' -Direction Inbound `
            -LocalPort 21027 -Protocol UDP -Action Allow `
            -Profile Private -Description 'Syncthing local discovery' | Out-Null
        Log "Created firewall rules (TCP $($Cfg.firewall.syncthing_port) + UDP 21027)" 'OK'; $script:changed++
    } catch {
        Log "Failed to create firewall rules: $($_.Exception.Message)" 'ERR'
    }
}

# ===========================================================================
# 5. Register as Windows service (via nssm or scheduled task)
# ===========================================================================
Write-Host ""
Write-Host "  Service" -ForegroundColor White

$syncService = Get-Service -Name 'Syncthing' -ErrorAction SilentlyContinue
if ($syncService) {
    Log "Syncthing service already registered (Status: $($syncService.Status))" 'SKIP'; $script:skipped++
    if ($syncService.Status -ne 'Running') {
        Start-Service 'Syncthing' -ErrorAction SilentlyContinue
        Log "Started Syncthing service" 'OK'
    }
} else {
    # Use a scheduled task as lightweight service (no NSSM dependency)
    $syncTask = Get-ScheduledTask -TaskName 'Syncthing' -ErrorAction SilentlyContinue
    if ($syncTask) {
        Log "Syncthing scheduled task exists" 'SKIP'; $script:skipped++
    } elseif ($PSCmdlet.ShouldProcess('Syncthing', 'Create startup task')) {
        try {
            $syncExe = (Get-Command syncthing).Source
            $action = New-ScheduledTaskAction -Execute $syncExe -Argument '-no-browser -no-restart'
            $trigger = New-ScheduledTaskTrigger -AtStartup
            $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -ExecutionTimeLimit ([TimeSpan]::Zero)
            $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -RunLevel Highest -LogonType S4U
            Register-ScheduledTask -TaskName 'Syncthing' -Action $action -Trigger $trigger `
                -Settings $settings -Principal $principal -Description 'Syncthing asset pre-staging' | Out-Null
            Log "Created startup task 'Syncthing'" 'OK'; $script:changed++

            # Start it now
            Start-ScheduledTask -TaskName 'Syncthing'
            Start-Sleep 3
            $syncProc = Get-Process -Name 'syncthing' -ErrorAction SilentlyContinue
            if ($syncProc) {
                Log "Syncthing started (PID $($syncProc.Id))" 'OK'
            } else {
                Log "Syncthing task created but process not detected yet" 'WARN'
            }
        } catch {
            Log "Failed to create task: $($_.Exception.Message)" 'ERR'
        }
    }
}

# ===========================================================================
# Summary
# ===========================================================================
Write-Host ""
Write-Host "  --- Summary ---" -ForegroundColor Cyan
Write-Host "  Changed: $($script:changed)  Skipped: $($script:skipped)" -ForegroundColor $(if ($script:changed -gt 0) { 'Green' } else { 'DarkGray' })

Write-Host ""
Write-Host "  --- Next Steps ---" -ForegroundColor Yellow
Write-Host "  1. Open Syncthing web UI: http://localhost:8384" -ForegroundColor White
Write-Host "  2. Add folder: $($Cfg.server.storage_root) (set as Send Only)" -ForegroundColor White
Write-Host "  3. Connect remote device (monolith): Add Device by ID" -ForegroundColor White
Write-Host "     monolith already runs Syncthing (godot-sync container)" -ForegroundColor DarkGray
Write-Host "  4. Share the folder with monolith (set monolith as Receive Only)" -ForegroundColor White
Write-Host ""
Write-Host "  Folders to sync:" -ForegroundColor DarkGray
foreach ($folder in $Cfg.syncthing.sync_folders) {
    $fullPath = Join-Path $Cfg.server.storage_root $folder
    Write-Host "    $fullPath" -ForegroundColor DarkGray
}
Write-Host ""
